[package]
name = "crab-proxy"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
crab-metrics.workspace = true
crab-route.workspace = true
crab-cache.workspace = true
crab-semantic.workspace = true
crab-reasoning.workspace = true
crab-pipeline.workspace = true
crab-translator.workspace = true
crab-control.workspace = true
crab-client-endpoint.workspace = true
pingora.workspace = true
pingora-core.workspace = true
pingora-proxy.workspace = true
pingora-http.workspace = true
pingora-limits.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
bytes.workspace = true
moka.workspace = true
anyhow.workspace = true
tracing.workspace = true
async-trait.workspace = true
uuid.workspace = true
http.workspace = true
tokio.workspace = true
dashmap.workspace = true
parking_lot.workspace = true
crab-composition.workspace = true
crab-capture.workspace = true
sha2.workspace = true
hex.workspace = true
memchr.workspace = true
chrono.workspace = true
thiserror.workspace = true
indexmap = { workspace = true }
regex.workspace = true
flate2 = "1"
brotli = "7"
bb8.workspace = true
bb8-redis.workspace = true
redis.workspace = true
once_cell.workspace = true
reqwest.workspace = true

[features]
default = []
fault-injection = []
