[package]
name = "crab-cache"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
crab-metrics.workspace = true
moka.workspace = true
redis.workspace = true
bb8.workspace = true
bb8-redis.workspace = true
serde.workspace = true
serde_json.workspace = true
bytes.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
dashmap.workspace = true
parking_lot.workspace = true
sha2.workspace = true
hex.workspace = true
tokio.workspace = true
rand = "0.8"
async-trait.workspace = true
futures = "0.3"
md5 = "0.7"
unicode-normalization.workspace = true
