[package]
name = "crab-route"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
pingora-ketama.workspace = true
pingora-core.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
sha2.workspace = true
hex.workspace = true
http.workspace = true
