[package]
name = "crab-route"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
pingora-ketama.workspace = true
pingora-core.workspace = true
pingora-load-balancing.workspace = true
async-trait.workspace = true
tracing.workspace = true
thiserror.workspace = true
anyhow.workspace = true
sha2.workspace = true
hex.workspace = true
http.workspace = true
serde.workspace = true
arc-swap.workspace = true
crab-metrics.workspace = true
tokio.workspace = true
futures = "0.3"
