use once_cell::sync::Lazy;
use prometheus::{
    CounterVec, HistogramOpts, HistogramVec, IntCounter, IntCounterVec, Opts, Registry,
};
use std::time::Duration;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CacheTier {
    L0Moka,
    L1Redis,
    L2Semantic,
    Miss,
}

impl CacheTier {
    pub fn as_str(&self) -> &'static str {
        match self {
            CacheTier::L0Moka => "L0_moka",
            CacheTier::L1Redis => "L1_redis",
            CacheTier::L2Semantic => "L2_semantic",
            CacheTier::Miss => "miss",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LatencyKind {
    Upstream,
    TTFT,
    CacheFetch,
}

impl LatencyKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            LatencyKind::Upstream => "upstream",
            LatencyKind::TTFT => "ttft",
            LatencyKind::CacheFetch => "cache_fetch",
        }
    }
}

pub struct GatewayMetrics {
    pub input_tokens: IntCounterVec,
    pub output_tokens: IntCounterVec,
    pub cache_requests: IntCounterVec,
    pub upstream_latency: HistogramVec,
    pub ttft: HistogramVec,
    pub cache_fetch_latency: HistogramVec,
    pub semantic_requests: IntCounterVec,
    pub embed_latency: HistogramVec,
    pub skipped_requests: IntCounterVec,
    pub coalesced_requests: IntCounter,
    pub cost_saved_usd: CounterVec,
    pub upstream_prompt_cache_tokens: IntCounterVec,
    pub stream_cache_sse_omitted: IntCounterVec,
    pub rejected_requests: IntCounterVec,
}

impl GatewayMetrics {
    fn new() -> Result<Self, prometheus::Error> {
        let input_tokens = IntCounterVec::new(
            Opts::new(
                "gateway_deepseek_input_tokens_total",
                "Total number of input tokens processed by DeepSeek",
            ),
            &["cache_status", "model", "consumer"],
        )?;

        let output_tokens = IntCounterVec::new(
            Opts::new(
                "gateway_deepseek_output_tokens_total",
                "Total number of output tokens generated by DeepSeek",
            ),
            &["model", "consumer"],
        )?;

        let cache_requests = IntCounterVec::new(
            Opts::new(
                "gateway_cache_requests_total",
                "Total number of cache requests by tier and result",
            ),
            &["tier", "result"],
        )?;

        let upstream_latency = HistogramVec::new(
            HistogramOpts::new(
                "gateway_upstream_latency_seconds",
                "Upstream response latency in seconds",
            )
            .buckets(vec![
                0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0,
            ]),
            &["model"],
        )?;

        let ttft = HistogramVec::new(
            HistogramOpts::new(
                "gateway_stream_first_token_latency_seconds",
                "Time to first token latency in seconds for streaming responses",
            )
            .buckets(vec![
                0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0, 30.0,
            ]),
            &["model"],
        )?;

        let cache_fetch_latency = HistogramVec::new(
            HistogramOpts::new(
                "gateway_cache_fetch_latency_seconds",
                "Cache fetch latency in seconds",
            )
            .buckets(vec![0.000_001, 0.000_01, 0.000_1, 0.001, 0.005, 0.01, 0.05, 0.1]),
            &["tier"],
        )?;

        let embed_latency = HistogramVec::new(
            HistogramOpts::new(
                "gateway_semantic_embed_latency_seconds",
                "Semantic embed latency in seconds",
            )
            .buckets(vec![
                0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0,
            ]),
            &[],
        )?;

        let skipped_requests = IntCounterVec::new(
            Opts::new(
                "gateway_semantic_skipped_total",
                "Total number of semantic search skips by reason",
            ),
            &["reason"],
        )?;

        let semantic_requests = IntCounterVec::new(
            Opts::new(
                "gateway_semantic_cache_requests_total",
                "Total number of semantic cache requests by status",
            ),
            &["status"],
        )?;

        let coalesced_requests = IntCounter::new(
            "gateway_coalesced_requests_total",
            "Total number of coalesced requests (duplicate concurrent requests)",
        )?;

        let cost_saved_usd = CounterVec::new(
            Opts::new(
                "gateway_cache_cost_saved_usd_total",
                "Total cost saved by cache hits in USD",
            ),
            &["model", "consumer", "tier"],
        )?;

        let upstream_prompt_cache_tokens = IntCounterVec::new(
            Opts::new(
                "gateway_upstream_prompt_cache_tokens_total",
                "Total upstream prompt cache tokens by status",
            ),
            &["status", "model", "consumer"],
        )?;

        let stream_cache_sse_omitted = IntCounterVec::new(
            Opts::new(
                "gateway_stream_cache_sse_omitted_total",
                "Stream cache writes that omitted raw SSE body",
            ),
            &["reason"],
        )?;

        let rejected_requests = IntCounterVec::new(
            Opts::new(
                "gateway_rejected_requests_total",
                "Requests rejected before upstream (overload, body limit, etc.)",
            ),
            &["reason"],
        )?;

        Ok(Self {
            input_tokens,
            output_tokens,
            cache_requests,
            upstream_latency,
            ttft,
            cache_fetch_latency,
            semantic_requests,
            embed_latency,
            skipped_requests,
            coalesced_requests,
            cost_saved_usd,
            upstream_prompt_cache_tokens,
            stream_cache_sse_omitted,
            rejected_requests,
        })
    }

    pub fn register(&self, registry: &Registry) -> Result<(), prometheus::Error> {
        registry.register(Box::new(self.input_tokens.clone()))?;
        registry.register(Box::new(self.output_tokens.clone()))?;
        registry.register(Box::new(self.cache_requests.clone()))?;
        registry.register(Box::new(self.upstream_latency.clone()))?;
        registry.register(Box::new(self.ttft.clone()))?;
        registry.register(Box::new(self.cache_fetch_latency.clone()))?;
        registry.register(Box::new(self.semantic_requests.clone()))?;
        registry.register(Box::new(self.embed_latency.clone()))?;
        registry.register(Box::new(self.skipped_requests.clone()))?;
        registry.register(Box::new(self.coalesced_requests.clone()))?;
        registry.register(Box::new(self.cost_saved_usd.clone()))?;
        registry.register(Box::new(self.upstream_prompt_cache_tokens.clone()))?;
        registry.register(Box::new(self.stream_cache_sse_omitted.clone()))?;
        registry.register(Box::new(self.rejected_requests.clone()))?;
        Ok(())
    }

    pub fn record_rejected(&self, reason: &str) {
        self.rejected_requests.with_label_values(&[reason]).inc();
    }

    pub fn record_stream_cache_sse_omitted(&self, reason: &str) {
        self.stream_cache_sse_omitted
            .with_label_values(&[reason])
            .inc();
    }

    pub fn record_cache_hit(&self, tier: CacheTier, model: &str, consumer: Option<&str>) {
        let consumer = consumer.unwrap_or("unknown");
        let result = if tier == CacheTier::Miss {
            "miss"
        } else {
            "hit"
        };

        self.cache_requests
            .with_label_values(&[tier.as_str(), result])
            .inc();

        if tier != CacheTier::Miss {
            tracing::debug!(
                tier = tier.as_str(),
                model = model,
                consumer = consumer,
                "Cache hit recorded"
            );
        }
    }

    pub fn record_cache_miss(&self, tier: CacheTier) {
        self.cache_requests
            .with_label_values(&[tier.as_str(), "miss"])
            .inc();
    }

    pub fn record_upstream_usage(
        &self,
        prompt_tokens: u64,
        completion_tokens: u64,
        cache_hit_tokens: u64,
        cache_miss_tokens: u64,
        model: &str,
        consumer: Option<&str>,
    ) {
        let consumer = consumer.unwrap_or("unknown");

        self.input_tokens
            .with_label_values(&["hit", model, consumer])
            .inc_by(cache_hit_tokens);

        self.input_tokens
            .with_label_values(&["miss", model, consumer])
            .inc_by(cache_miss_tokens);

        self.output_tokens
            .with_label_values(&[model, consumer])
            .inc_by(completion_tokens);

        tracing::debug!(
            model = model,
            consumer = consumer,
            prompt_tokens = prompt_tokens,
            completion_tokens = completion_tokens,
            cache_hit_tokens = cache_hit_tokens,
            cache_miss_tokens = cache_miss_tokens,
            "Upstream usage recorded"
        );
    }

    pub fn record_latency(
        &self,
        kind: LatencyKind,
        duration: Duration,
        model: &str,
        tier: Option<CacheTier>,
    ) {
        let duration_secs = duration.as_secs_f64();

        match kind {
            LatencyKind::Upstream => {
                self.upstream_latency
                    .with_label_values(&[model])
                    .observe(duration_secs);
            }
            LatencyKind::TTFT => {
                self.ttft
                    .with_label_values(&[model])
                    .observe(duration_secs);
            }
            LatencyKind::CacheFetch => {
                if let Some(tier) = tier {
                    self.cache_fetch_latency
                        .with_label_values(&[tier.as_str()])
                        .observe(duration_secs);
                }
            }
        }

        tracing::trace!(
            kind = kind.as_str(),
            duration_secs = duration_secs,
            model = model,
            tier = tier.map(|t| t.as_str()),
            "Latency recorded"
        );
    }

    pub fn record_semantic_cache_hit(&self, above_threshold: bool) {
        let status = if above_threshold {
            "hit_above_threshold"
        } else {
            "hit_below_threshold"
        };
        self.semantic_requests.with_label_values(&[status]).inc();
    }

    pub fn record_semantic_cache_rejected(&self) {
        self.semantic_requests
            .with_label_values(&["rejected_by_guard"])
            .inc();
    }

    pub fn record_semantic_embed_latency(&self, duration: Duration) {
        self.embed_latency
            .with_label_values(&[])
            .observe(duration.as_secs_f64());
    }

    pub fn record_semantic_skipped(&self, reason: &str) {
        self.skipped_requests
            .with_label_values(&[reason])
            .inc();
    }

    pub fn record_coalesced_request(&self) {
        self.coalesced_requests.inc();
    }

    pub fn record_cost_saved(&self, model: &str, consumer: Option<&str>, tier: CacheTier, usd: f64) {
        let consumer = consumer.unwrap_or("unknown");
        self.cost_saved_usd
            .with_label_values(&[model, consumer, tier.as_str()])
            .inc_by(usd);
    }

    pub fn record_upstream_prompt_cache(
        &self,
        status: &str,
        tokens: u64,
        model: &str,
        consumer: Option<&str>,
    ) {
        let consumer = consumer.unwrap_or("unknown");
        self.upstream_prompt_cache_tokens
            .with_label_values(&[status, model, consumer])
            .inc_by(tokens);
    }
}

static GLOBAL_METRICS: Lazy<GatewayMetrics> = Lazy::new(|| {
    GatewayMetrics::new().expect("Failed to create global metrics")
});

pub fn global_metrics() -> &'static GatewayMetrics {
    &GLOBAL_METRICS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cache_tier_as_str() {
        assert_eq!(CacheTier::L0Moka.as_str(), "L0_moka");
        assert_eq!(CacheTier::L1Redis.as_str(), "L1_redis");
        assert_eq!(CacheTier::L2Semantic.as_str(), "L2_semantic");
        assert_eq!(CacheTier::Miss.as_str(), "miss");
    }

    #[test]
    fn test_latency_kind_as_str() {
        assert_eq!(LatencyKind::Upstream.as_str(), "upstream");
        assert_eq!(LatencyKind::TTFT.as_str(), "ttft");
        assert_eq!(LatencyKind::CacheFetch.as_str(), "cache_fetch");
    }

    #[test]
    fn test_global_metrics_creation() {
        let metrics = global_metrics();
        assert!(std::ptr::eq(metrics, global_metrics()));
    }

    #[test]
    fn test_metrics_registration() {
        let metrics = GatewayMetrics::new().expect("Failed to create metrics");
        let registry = Registry::new();
        assert!(metrics.register(&registry).is_ok());
    }

    #[test]
    fn test_record_cache_hit() {
        let metrics = global_metrics();
        metrics.record_cache_hit(CacheTier::L0Moka, "v4-pro", Some("test_consumer"));
    }

    #[test]
    fn test_record_upstream_usage() {
        let metrics = global_metrics();
        metrics.record_upstream_usage(100, 50, 80, 20, "v4-pro", Some("test_consumer"));
    }

    #[test]
    fn test_record_latency() {
        let metrics = global_metrics();
        metrics.record_latency(
            LatencyKind::Upstream,
            Duration::from_millis(100),
            "v4-pro",
            None,
        );
        metrics.record_latency(
            LatencyKind::CacheFetch,
            Duration::from_micros(500),
            "v4-pro",
            Some(CacheTier::L0Moka),
        );
    }
}
