use once_cell::sync::Lazy;
use prometheus::{
    CounterVec, HistogramOpts, HistogramVec, IntCounter, IntCounterVec, IntGaugeVec, Opts, Registry,
};
use std::time::Duration;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum CacheTier {
    L0Moka,
    L1Redis,
    L2Semantic,
    Miss,
}

impl CacheTier {
    pub fn as_str(&self) -> &'static str {
        match self {
            CacheTier::L0Moka => "L0_moka",
            CacheTier::L1Redis => "L1_redis",
            CacheTier::L2Semantic => "L2_semantic",
            CacheTier::Miss => "miss",
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LatencyKind {
    Upstream,
    TTFT,
    CacheFetch,
}

fn metric_consumer(consumer: Option<&str>) -> &str {
    consumer.unwrap_or("unknown")
}

fn metric_domain(domain: Option<&str>) -> &str {
    domain.unwrap_or("unclassified")
}

impl LatencyKind {
    pub fn as_str(&self) -> &'static str {
        match self {
            LatencyKind::Upstream => "upstream",
            LatencyKind::TTFT => "ttft",
            LatencyKind::CacheFetch => "cache_fetch",
        }
    }
}

pub struct GatewayMetrics {
    pub input_tokens: IntCounterVec,
    pub output_tokens: IntCounterVec,
    pub cache_requests: IntCounterVec,
    pub upstream_latency: HistogramVec,
    pub ttft: HistogramVec,
    pub cache_fetch_latency: HistogramVec,
    pub semantic_requests: IntCounterVec,
    pub embed_latency: HistogramVec,
    pub skipped_requests: IntCounterVec,
    pub coalesced_requests: IntCounter,
    pub cost_saved_usd: CounterVec,
    pub upstream_prompt_cache_tokens: IntCounterVec,
    pub stream_cache_sse_omitted: IntCounterVec,
    pub rejected_requests: IntCounterVec,
    pub upstream_key_requests: IntCounterVec,
    pub upstream_key_inflight: IntGaugeVec,
    pub client_key_inflight: IntGaugeVec,
    pub upstream_key_retries: IntCounterVec,
    pub reasoning_store_lookups: IntCounterVec,
    pub prefix_break: IntCounter,
    pub prefix_block_drift: IntCounter,
    pub context_summary_appended: IntCounter,
    pub state_persist_total: IntCounter,
    pub state_persist_errors_total: IntCounter,
    pub reasoning_store_rejected_bytes: IntCounter,
    pub pipeline_selected: IntCounterVec,
    pub composition_requests: IntCounterVec,
    pub composition_component: IntCounterVec,
    pub composition_tool_count: HistogramVec,
    pub deepseek_user_id_concurrency_rejected: IntCounterVec,
    pub deepseek_user_id_inflight: IntGaugeVec,
    pub http_responses: IntCounterVec,
    pub upstream_key_input_tokens: IntCounterVec,
    pub upstream_key_output_tokens: IntCounterVec,
    pub upstream_key_latency: HistogramVec,
    pub backend_requests: IntCounterVec,
    pub request_body_stage_latency: HistogramVec,
    pub request_body_stage_samples: IntCounterVec,
    pub raw_capture_samples: IntCounterVec,
    pub session_prompt_cache_tokens: IntCounterVec,
    pub full_response_cache_hits: IntCounterVec,
    pub requests_saved_by_any_cache: IntCounterVec,
    pub admin_log_writes_total: IntCounterVec,
    pub admin_log_pg_write_errors_total: IntCounter,
    pub admin_log_disk_bytes: IntGaugeVec,
    pub admin_log_pg_rows: IntGaugeVec,
}

impl GatewayMetrics {
    fn new() -> Result<Self, prometheus::Error> {
        let input_tokens = IntCounterVec::new(
            Opts::new(
                "gateway_deepseek_input_tokens_total",
                "Total number of input tokens processed by DeepSeek",
            ),
            &["cache_status", "model", "consumer", "domain"],
        )?;

        let output_tokens = IntCounterVec::new(
            Opts::new(
                "gateway_deepseek_output_tokens_total",
                "Total number of output tokens generated by DeepSeek",
            ),
            &["model", "consumer", "domain"],
        )?;

        let cache_requests = IntCounterVec::new(
            Opts::new(
                "gateway_cache_requests_total",
                "Total number of cache requests by tier and result",
            ),
            &["tier", "result", "domain"],
        )?;

        let upstream_latency = HistogramVec::new(
            HistogramOpts::new(
                "gateway_upstream_latency_seconds",
                "Upstream response latency in seconds",
            )
            .buckets(vec![0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0]),
            &["model"],
        )?;

        let ttft = HistogramVec::new(
            HistogramOpts::new(
                "gateway_stream_first_token_latency_seconds",
                "Time to first token latency in seconds for streaming responses",
            )
            .buckets(vec![0.1, 0.25, 0.5, 1.0, 2.0, 3.0, 5.0, 10.0, 20.0, 30.0]),
            &["model"],
        )?;

        let cache_fetch_latency = HistogramVec::new(
            HistogramOpts::new(
                "gateway_cache_fetch_latency_seconds",
                "Cache fetch latency in seconds",
            )
            .buckets(vec![
                0.000_001, 0.000_01, 0.000_1, 0.001, 0.005, 0.01, 0.05, 0.1,
            ]),
            &["tier"],
        )?;

        let embed_latency = HistogramVec::new(
            HistogramOpts::new(
                "gateway_semantic_embed_latency_seconds",
                "Semantic embed latency in seconds",
            )
            .buckets(vec![
                0.001, 0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0,
            ]),
            &[],
        )?;

        let skipped_requests = IntCounterVec::new(
            Opts::new(
                "gateway_semantic_skipped_total",
                "Total number of semantic search skips by reason",
            ),
            &["reason"],
        )?;

        let semantic_requests = IntCounterVec::new(
            Opts::new(
                "gateway_semantic_cache_requests_total",
                "Total number of semantic cache requests by status",
            ),
            &["status"],
        )?;

        let coalesced_requests = IntCounter::new(
            "gateway_coalesced_requests_total",
            "Total number of coalesced requests (duplicate concurrent requests)",
        )?;

        let cost_saved_usd = CounterVec::new(
            Opts::new(
                "gateway_cache_cost_saved_usd_total",
                "Total cost saved by cache hits in USD",
            ),
            &["model", "consumer", "tier", "domain"],
        )?;

        let upstream_prompt_cache_tokens = IntCounterVec::new(
            Opts::new(
                "gateway_upstream_prompt_cache_tokens_total",
                "Total upstream prompt cache tokens by status",
            ),
            &["status", "model", "consumer", "domain"],
        )?;

        let stream_cache_sse_omitted = IntCounterVec::new(
            Opts::new(
                "gateway_stream_cache_sse_omitted_total",
                "Stream cache writes that omitted raw SSE body",
            ),
            &["reason"],
        )?;

        let rejected_requests = IntCounterVec::new(
            Opts::new(
                "gateway_rejected_requests_total",
                "Requests rejected before upstream (overload, body limit, etc.)",
            ),
            &["reason"],
        )?;

        let upstream_key_requests = IntCounterVec::new(
            Opts::new(
                "gateway_upstream_key_requests_total",
                "Upstream DeepSeek API key pool requests by key id and result",
            ),
            &["key_id", "result"],
        )?;

        let upstream_key_inflight = IntGaugeVec::new(
            Opts::new(
                "gateway_upstream_key_inflight",
                "In-flight upstream requests per DeepSeek API key id",
            ),
            &["key_id"],
        )?;

        let client_key_inflight = IntGaugeVec::new(
            Opts::new(
                "gateway_client_key_inflight",
                "In-flight client API key requests by key id and consumer name",
            ),
            &["key_id", "consumer"],
        )?;

        let upstream_key_retries = IntCounterVec::new(
            Opts::new(
                "gateway_upstream_key_retries_total",
                "Upstream key rotation attempts after rate limit (same-request retry not yet supported for streaming)",
            ),
            &["outcome"],
        )?;

        let reasoning_store_lookups = IntCounterVec::new(
            Opts::new(
                "gateway_reasoning_store_lookups_total",
                "ReasoningStore get() results during message normalization",
            ),
            &["result"],
        )?;

        let prefix_break = IntCounter::new(
            "gateway_prefix_break_total",
            "Detected non-append-only message prefix changes vs cached scope",
        )?;

        let prefix_block_drift = IntCounter::new(
            "gateway_prefix_block_drift_total",
            "Immutable leading system/tools block hash drift for a conversation scope",
        )?;

        let context_summary_appended = IntCounter::new(
            "gateway_context_summary_appended_total",
            "Context summary messages appended at tail (strategy B)",
        )?;

        let state_persist_total = IntCounter::new(
            "gateway_state_persist_total",
            "Successful control-plane state writes to Redis",
        )?;

        let state_persist_errors_total = IntCounter::new(
            "gateway_state_persist_errors_total",
            "Failed control-plane state writes to Redis after retries",
        )?;

        let reasoning_store_rejected_bytes = IntCounter::new(
            "gateway_reasoning_store_rejected_bytes_total",
            "Reasoning cache entries rejected due to max_reasoning_entry_bytes",
        )?;

        let pipeline_selected = IntCounterVec::new(
            Opts::new(
                "gateway_pipeline_selected_total",
                "Request pipeline selections by pipeline, upstream profile, and reason",
            ),
            &["pipeline", "profile", "reason"],
        )?;

        let composition_requests = IntCounterVec::new(
            Opts::new(
                "gateway_composition_requests_total",
                "Request composition counts by pipeline, has_tools, and message count bucket",
            ),
            &["pipeline", "has_tools", "msg_bucket"],
        )?;

        let composition_component = IntCounterVec::new(
            Opts::new(
                "gateway_composition_component_total",
                "Cursor component detection counts by component name and presence",
            ),
            &["component", "present"],
        )?;

        let composition_tool_count = HistogramVec::new(
            HistogramOpts::new(
                "gateway_composition_tool_count",
                "Distribution of tool count per request",
            )
            .buckets(vec![0.0, 1.0, 5.0, 10.0, 20.0, 50.0]),
            &[],
        )?;

        let deepseek_user_id_concurrency_rejected = IntCounterVec::new(
            Opts::new(
                "gateway_deepseek_user_id_concurrency_rejected_total",
                "Gateway-side rejections when per-user_id DeepSeek v4 concurrency soft limit is exceeded",
            ),
            &["tier"],
        )?;

        let deepseek_user_id_inflight = IntGaugeVec::new(
            Opts::new(
                "gateway_deepseek_user_id_inflight",
                "Aggregate in-flight upstream chat requests counted against per-user_id limits (by model tier)",
            ),
            &["tier"],
        )?;

        let http_responses = IntCounterVec::new(
            Opts::new(
                "gateway_http_responses_total",
                "Total HTTP responses by status class",
            ),
            &["status_class"],
        )?;

        let upstream_key_input_tokens = IntCounterVec::new(
            Opts::new(
                "gateway_upstream_key_input_tokens_total",
                "Total input tokens per upstream key id and model",
            ),
            &["key_id", "model"],
        )?;

        let upstream_key_output_tokens = IntCounterVec::new(
            Opts::new(
                "gateway_upstream_key_output_tokens_total",
                "Total output tokens per upstream key id and model",
            ),
            &["key_id", "model"],
        )?;

        let upstream_key_latency = HistogramVec::new(
            HistogramOpts::new(
                "gateway_upstream_key_latency_seconds",
                "Upstream response latency per key id in seconds",
            )
            .buckets(vec![0.1, 0.5, 1.0, 2.0, 5.0, 10.0, 20.0, 30.0, 60.0, 120.0]),
            &["key_id"],
        )?;

        let backend_requests = IntCounterVec::new(
            Opts::new(
                "gateway_backend_requests_total",
                "Total requests per upstream backend node",
            ),
            &["backend_name", "result"],
        )?;

        let request_body_stage_latency = HistogramVec::new(
            HistogramOpts::new(
                "gateway_request_body_stage_latency_seconds",
                "Request-body processing stage latency in seconds",
            )
            .buckets(vec![
                0.0005, 0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2, 0.5, 1.0,
            ]),
            &["stage", "size_bucket", "pipeline"],
        )?;

        let request_body_stage_samples = IntCounterVec::new(
            Opts::new(
                "gateway_request_body_stage_samples_total",
                "Request-body stage sample count by size bucket and pipeline",
            ),
            &["stage", "size_bucket", "pipeline"],
        )?;

        let raw_capture_samples = IntCounterVec::new(
            Opts::new(
                "gateway_raw_capture_samples_total",
                "Raw capture sampling decisions by outcome",
            ),
            &["outcome"],
        )?;

        let session_prompt_cache_tokens = IntCounterVec::new(
            Opts::new(
                "gateway_session_prompt_cache_tokens_total",
                "Upstream prompt cache tokens grouped by affinity kind, status, and model",
            ),
            &["affinity_kind", "status", "model"],
        )?;

        let full_response_cache_hits = IntCounterVec::new(
            Opts::new(
                "gateway_full_response_cache_hits_total",
                "Full response cache hits by tier and domain (avoided upstream inference)",
            ),
            &["tier", "domain"],
        )?;

        let requests_saved_by_any_cache = IntCounterVec::new(
            Opts::new(
                "gateway_requests_saved_by_any_cache_total",
                "Requests saved from full inference by any cache mechanism (exact, prefix, semantic)",
            ),
            &["domain"],
        )?;

        let admin_log_writes_total = IntCounterVec::new(
            Opts::new(
                "admin_log_writes_total",
                "Total log entries written to PostgreSQL by type",
            ),
            &["type"],
        )?;

        let admin_log_pg_write_errors_total = IntCounter::new(
            "admin_log_pg_write_errors_total",
            "Total PostgreSQL write errors in the log subsystem",
        )?;

        let admin_log_disk_bytes = IntGaugeVec::new(
            Opts::new(
                "admin_log_disk_bytes",
                "Disk usage in bytes for log files by type",
            ),
            &["type"],
        )?;

        let admin_log_pg_rows = IntGaugeVec::new(
            Opts::new(
                "admin_log_pg_rows",
                "Row count in PostgreSQL log tables",
            ),
            &["table"],
        )?;

        Ok(Self {
            input_tokens,
            output_tokens,
            cache_requests,
            upstream_latency,
            ttft,
            cache_fetch_latency,
            semantic_requests,
            embed_latency,
            skipped_requests,
            coalesced_requests,
            cost_saved_usd,
            upstream_prompt_cache_tokens,
            stream_cache_sse_omitted,
            rejected_requests,
            upstream_key_requests,
            upstream_key_inflight,
            client_key_inflight,
            upstream_key_retries,
            reasoning_store_lookups,
            prefix_break,
            prefix_block_drift,
            context_summary_appended,
            state_persist_total,
            state_persist_errors_total,
            reasoning_store_rejected_bytes,
            pipeline_selected,
            composition_requests,
            composition_component,
            composition_tool_count,
            deepseek_user_id_concurrency_rejected,
            deepseek_user_id_inflight,
            http_responses,
            upstream_key_input_tokens,
            upstream_key_output_tokens,
            upstream_key_latency,
            backend_requests,
            request_body_stage_latency,
            request_body_stage_samples,
            raw_capture_samples,
            session_prompt_cache_tokens,
            full_response_cache_hits,
            requests_saved_by_any_cache,
            admin_log_writes_total,
            admin_log_pg_write_errors_total,
            admin_log_disk_bytes,
            admin_log_pg_rows,
        })
    }

    pub fn register(&self, registry: &Registry) -> Result<(), prometheus::Error> {
        registry.register(Box::new(self.input_tokens.clone()))?;
        registry.register(Box::new(self.output_tokens.clone()))?;
        registry.register(Box::new(self.cache_requests.clone()))?;
        registry.register(Box::new(self.upstream_latency.clone()))?;
        registry.register(Box::new(self.ttft.clone()))?;
        registry.register(Box::new(self.cache_fetch_latency.clone()))?;
        registry.register(Box::new(self.semantic_requests.clone()))?;
        registry.register(Box::new(self.embed_latency.clone()))?;
        registry.register(Box::new(self.skipped_requests.clone()))?;
        registry.register(Box::new(self.coalesced_requests.clone()))?;
        registry.register(Box::new(self.cost_saved_usd.clone()))?;
        registry.register(Box::new(self.upstream_prompt_cache_tokens.clone()))?;
        registry.register(Box::new(self.stream_cache_sse_omitted.clone()))?;
        registry.register(Box::new(self.rejected_requests.clone()))?;
        registry.register(Box::new(self.upstream_key_requests.clone()))?;
        registry.register(Box::new(self.upstream_key_inflight.clone()))?;
        registry.register(Box::new(self.client_key_inflight.clone()))?;
        registry.register(Box::new(self.upstream_key_retries.clone()))?;
        registry.register(Box::new(self.reasoning_store_lookups.clone()))?;
        registry.register(Box::new(self.prefix_break.clone()))?;
        registry.register(Box::new(self.prefix_block_drift.clone()))?;
        registry.register(Box::new(self.context_summary_appended.clone()))?;
        registry.register(Box::new(self.state_persist_total.clone()))?;
        registry.register(Box::new(self.state_persist_errors_total.clone()))?;
        registry.register(Box::new(self.reasoning_store_rejected_bytes.clone()))?;
        registry.register(Box::new(self.pipeline_selected.clone()))?;
        registry.register(Box::new(self.composition_requests.clone()))?;
        registry.register(Box::new(self.composition_component.clone()))?;
        registry.register(Box::new(self.composition_tool_count.clone()))?;
        registry.register(Box::new(self.deepseek_user_id_concurrency_rejected.clone()))?;
        registry.register(Box::new(self.deepseek_user_id_inflight.clone()))?;
        registry.register(Box::new(self.http_responses.clone()))?;
        registry.register(Box::new(self.upstream_key_input_tokens.clone()))?;
        registry.register(Box::new(self.upstream_key_output_tokens.clone()))?;
        registry.register(Box::new(self.upstream_key_latency.clone()))?;
        registry.register(Box::new(self.backend_requests.clone()))?;
        registry.register(Box::new(self.request_body_stage_latency.clone()))?;
        registry.register(Box::new(self.request_body_stage_samples.clone()))?;
        registry.register(Box::new(self.raw_capture_samples.clone()))?;
        registry.register(Box::new(self.session_prompt_cache_tokens.clone()))?;
        registry.register(Box::new(self.full_response_cache_hits.clone()))?;
        registry.register(Box::new(self.requests_saved_by_any_cache.clone()))?;
        registry.register(Box::new(self.admin_log_writes_total.clone()))?;
        registry.register(Box::new(self.admin_log_pg_write_errors_total.clone()))?;
        registry.register(Box::new(self.admin_log_disk_bytes.clone()))?;
        registry.register(Box::new(self.admin_log_pg_rows.clone()))?;
        Ok(())
    }

    pub fn record_deepseek_user_id_concurrency_rejected(&self, tier: &str) {
        self.deepseek_user_id_concurrency_rejected
            .with_label_values(&[tier])
            .inc();
    }

    pub fn set_deepseek_user_id_inflight(&self, tier: &str, value: i64) {
        self.deepseek_user_id_inflight
            .with_label_values(&[tier])
            .set(value);
    }

    pub fn record_pipeline_selected(&self, pipeline: &str, profile: &str, reason: &str) {
        self.pipeline_selected
            .with_label_values(&[pipeline, profile, reason])
            .inc();
    }

    pub fn record_http_response(&self, status: u16) {
        let class = match status / 100 {
            2 => "2xx",
            3 => "3xx",
            4 => "4xx",
            _ => "5xx",
        };
        self.http_responses.with_label_values(&[class]).inc();
    }

    pub fn record_composition_metrics(&self, comp: &crab_composition::RequestComposition) {
        let has_tools = if comp.has_tools { "true" } else { "false" };
        let mc = comp.message_count;
        let msg_bucket = if mc <= 10 {
            "0-10"
        } else if mc <= 50 {
            "11-50"
        } else if mc <= 100 {
            "51-100"
        } else {
            "100+"
        };

        self.composition_requests
            .with_label_values(&[&comp.pipeline, has_tools, msg_bucket])
            .inc();

        // Component detection counters
        let components = [
            ("rules", comp.components.rules.present),
            ("skills", comp.components.skills.present),
            ("mcp", comp.components.mcp.present),
            ("subagent", comp.components.subagent.present),
        ];
        for (name, present) in &components {
            let present_str = if *present { "true" } else { "false" };
            self.composition_component
                .with_label_values(&[name, present_str])
                .inc();
        }

        // Tool count histogram
        self.composition_tool_count
            .with_label_values(&[])
            .observe(comp.tool_count as f64);
    }

    pub fn record_state_persist_success(&self) {
        self.state_persist_total.inc();
    }

    pub fn record_state_persist_error(&self) {
        self.state_persist_errors_total.inc();
    }

    pub fn record_reasoning_store_rejected(&self) {
        self.reasoning_store_rejected_bytes.inc();
    }

    pub fn record_reasoning_store_lookup(&self, hit: bool) {
        let result = if hit { "hit" } else { "miss" };
        self.reasoning_store_lookups
            .with_label_values(&[result])
            .inc();
    }

    pub fn record_prefix_break(&self) {
        self.prefix_break.inc();
    }

    pub fn record_prefix_block_drift(&self) {
        self.prefix_block_drift.inc();
    }

    pub fn record_context_summary_appended(&self) {
        self.context_summary_appended.inc();
    }

    pub fn set_upstream_key_inflight(&self, key_id: &str, inflight: i64) {
        self.upstream_key_inflight
            .with_label_values(&[key_id])
            .set(inflight);
    }

    pub fn set_client_key_inflight(&self, key_id: &str, consumer: &str, inflight: i64) {
        self.client_key_inflight
            .with_label_values(&[key_id, consumer])
            .set(inflight);
    }

    pub fn remove_client_key_inflight(&self, key_id: &str, consumer: &str) {
        let _ = self
            .client_key_inflight
            .remove_label_values(&[key_id, consumer]);
    }

    pub fn record_upstream_key_retry(&self, outcome: &str) {
        self.upstream_key_retries
            .with_label_values(&[outcome])
            .inc();
    }

    pub fn record_upstream_key_request(&self, key_id: &str, result: &str) {
        self.upstream_key_requests
            .with_label_values(&[key_id, result])
            .inc();
    }

    pub fn record_rejected(&self, reason: &str) {
        self.rejected_requests.with_label_values(&[reason]).inc();
    }

    pub fn record_stream_cache_sse_omitted(&self, reason: &str) {
        self.stream_cache_sse_omitted
            .with_label_values(&[reason])
            .inc();
    }

    pub fn record_cache_hit(
        &self,
        tier: CacheTier,
        model: &str,
        consumer: Option<&str>,
        domain: Option<&str>,
    ) {
        let consumer = metric_consumer(consumer);
        let domain = metric_domain(domain);
        let result = if tier == CacheTier::Miss {
            "miss"
        } else {
            "hit"
        };

        self.cache_requests
            .with_label_values(&[tier.as_str(), result, domain])
            .inc();

        if tier != CacheTier::Miss {
            tracing::debug!(
                tier = tier.as_str(),
                model = model,
                consumer = consumer,
                domain = domain,
                "Cache hit recorded"
            );
        }
    }

    pub fn record_cache_miss(&self, tier: CacheTier, domain: Option<&str>) {
        let domain = metric_domain(domain);
        self.cache_requests
            .with_label_values(&[tier.as_str(), "miss", domain])
            .inc();
    }

    /// Record a full-response cache hit (exact L0/L1, prefix-aware, or semantic).
    /// This is the "avoided upstream inference" signal.
    pub fn record_full_response_cache_hit(&self, tier: &str, domain: Option<&str>) {
        let domain = metric_domain(domain);
        self.full_response_cache_hits
            .with_label_values(&[tier, domain])
            .inc();
    }

    /// Record that a request was saved from full inference by any cache mechanism.
    /// Call exactly once per request that is served from cache (any tier).
    pub fn record_request_saved_by_cache(&self, domain: Option<&str>) {
        let domain = metric_domain(domain);
        self.requests_saved_by_any_cache
            .with_label_values(&[domain])
            .inc();
    }

    #[allow(clippy::too_many_arguments)]
    pub fn record_upstream_usage(
        &self,
        prompt_tokens: u64,
        completion_tokens: u64,
        cache_hit_tokens: u64,
        cache_miss_tokens: u64,
        model: &str,
        consumer: Option<&str>,
        domain: Option<&str>,
    ) {
        let consumer = metric_consumer(consumer);
        let domain = metric_domain(domain);

        self.input_tokens
            .with_label_values(&["hit", model, consumer, domain])
            .inc_by(cache_hit_tokens);

        self.input_tokens
            .with_label_values(&["miss", model, consumer, domain])
            .inc_by(cache_miss_tokens);

        self.output_tokens
            .with_label_values(&[model, consumer, domain])
            .inc_by(completion_tokens);

        tracing::debug!(
            model = model,
            consumer = consumer,
            domain = domain,
            prompt_tokens = prompt_tokens,
            completion_tokens = completion_tokens,
            cache_hit_tokens = cache_hit_tokens,
            cache_miss_tokens = cache_miss_tokens,
            "Upstream usage recorded"
        );
    }

    pub fn record_latency(
        &self,
        kind: LatencyKind,
        duration: Duration,
        model: &str,
        tier: Option<CacheTier>,
    ) {
        let duration_secs = duration.as_secs_f64();

        match kind {
            LatencyKind::Upstream => {
                self.upstream_latency
                    .with_label_values(&[model])
                    .observe(duration_secs);
            }
            LatencyKind::TTFT => {
                self.ttft.with_label_values(&[model]).observe(duration_secs);
            }
            LatencyKind::CacheFetch => {
                if let Some(tier) = tier {
                    self.cache_fetch_latency
                        .with_label_values(&[tier.as_str()])
                        .observe(duration_secs);
                }
            }
        }

        tracing::trace!(
            kind = kind.as_str(),
            duration_secs = duration_secs,
            model = model,
            tier = tier.map(|t| t.as_str()),
            "Latency recorded"
        );
    }

    pub fn record_semantic_cache_hit(&self, above_threshold: bool) {
        let status = if above_threshold {
            "hit_above_threshold"
        } else {
            "hit_below_threshold"
        };
        self.semantic_requests.with_label_values(&[status]).inc();
    }

    pub fn record_semantic_cache_rejected(&self) {
        self.semantic_requests
            .with_label_values(&["rejected_by_guard"])
            .inc();
    }

    pub fn record_semantic_embed_latency(&self, duration: Duration) {
        self.embed_latency
            .with_label_values(&[])
            .observe(duration.as_secs_f64());
    }

    pub fn record_semantic_skipped(&self, reason: &str) {
        self.skipped_requests.with_label_values(&[reason]).inc();
    }

    pub fn record_coalesced_request(&self) {
        self.coalesced_requests.inc();
    }

    pub fn record_cost_saved(
        &self,
        model: &str,
        consumer: Option<&str>,
        domain: Option<&str>,
        tier: CacheTier,
        usd: f64,
    ) {
        let consumer = metric_consumer(consumer);
        let domain = metric_domain(domain);
        self.cost_saved_usd
            .with_label_values(&[model, consumer, tier.as_str(), domain])
            .inc_by(usd);
    }

    pub fn record_upstream_prompt_cache(
        &self,
        status: &str,
        tokens: u64,
        model: &str,
        consumer: Option<&str>,
        domain: Option<&str>,
    ) {
        let consumer = metric_consumer(consumer);
        let domain = metric_domain(domain);
        self.upstream_prompt_cache_tokens
            .with_label_values(&[status, model, consumer, domain])
            .inc_by(tokens);
    }

    pub fn record_upstream_key_usage(
        &self,
        key_id: &str,
        model: &str,
        input_tokens: u64,
        output_tokens: u64,
    ) {
        self.upstream_key_input_tokens
            .with_label_values(&[key_id, model])
            .inc_by(input_tokens);
        self.upstream_key_output_tokens
            .with_label_values(&[key_id, model])
            .inc_by(output_tokens);
    }

    pub fn record_upstream_key_latency(&self, key_id: &str, duration: Duration) {
        self.upstream_key_latency
            .with_label_values(&[key_id])
            .observe(duration.as_secs_f64());
    }

    pub fn record_backend_request(&self, backend_name: &str, result: &str) {
        self.backend_requests
            .with_label_values(&[backend_name, result])
            .inc();
    }

    pub fn record_request_body_stage(
        &self,
        stage: &str,
        duration: Duration,
        body_bytes: usize,
        pipeline: Option<&str>,
    ) {
        let size_bucket = request_body_size_bucket(body_bytes);
        let pipeline = pipeline.unwrap_or("unknown");
        self.request_body_stage_latency
            .with_label_values(&[stage, size_bucket, pipeline])
            .observe(duration.as_secs_f64());
        self.request_body_stage_samples
            .with_label_values(&[stage, size_bucket, pipeline])
            .inc();
    }

    // ── Raw capture sampling metrics ──────────────────────────────────

    pub fn record_raw_capture_sample(&self, outcome: &str) {
        self.raw_capture_samples
            .with_label_values(&[outcome])
            .inc();
    }

    // ── Session prompt cache metrics ──────────────────────────────────

    pub fn record_session_prompt_cache(
        &self,
        affinity_kind: &str,
        status: &str,
        tokens: u64,
        model: &str,
    ) {
        self.session_prompt_cache_tokens
            .with_label_values(&[affinity_kind, status, model])
            .inc_by(tokens);
    }

    // ── Admin log metrics ───────────────────────────────────────────

    pub fn inc_admin_log_write(&self, log_type: &str) {
        self.admin_log_writes_total
            .with_label_values(&[log_type])
            .inc();
    }

    pub fn inc_admin_log_pg_write_error(&self) {
        self.admin_log_pg_write_errors_total.inc();
    }

    pub fn set_admin_log_disk_bytes(&self, log_type: &str, bytes: i64) {
        self.admin_log_disk_bytes
            .with_label_values(&[log_type])
            .set(bytes);
    }

    pub fn set_admin_log_pg_rows(&self, table: &str, rows: i64) {
        self.admin_log_pg_rows
            .with_label_values(&[table])
            .set(rows);
    }
}

fn request_body_size_bucket(body_bytes: usize) -> &'static str {
    if body_bytes <= 256 * 1024 {
        "le_256k"
    } else if body_bytes <= 1024 * 1024 {
        "le_1m"
    } else if body_bytes <= 2 * 1024 * 1024 {
        "le_2m"
    } else if body_bytes <= 4 * 1024 * 1024 {
        "le_4m"
    } else {
        "gt_4m"
    }
}

static GLOBAL_METRICS: Lazy<GatewayMetrics> =
    Lazy::new(|| GatewayMetrics::new().expect("Failed to create global metrics"));

pub fn global_metrics() -> &'static GatewayMetrics {
    &GLOBAL_METRICS
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_cache_tier_as_str() {
        assert_eq!(CacheTier::L0Moka.as_str(), "L0_moka");
        assert_eq!(CacheTier::L1Redis.as_str(), "L1_redis");
        assert_eq!(CacheTier::L2Semantic.as_str(), "L2_semantic");
        assert_eq!(CacheTier::Miss.as_str(), "miss");
    }

    #[test]
    fn test_latency_kind_as_str() {
        assert_eq!(LatencyKind::Upstream.as_str(), "upstream");
        assert_eq!(LatencyKind::TTFT.as_str(), "ttft");
        assert_eq!(LatencyKind::CacheFetch.as_str(), "cache_fetch");
    }

    #[test]
    fn test_global_metrics_creation() {
        let metrics = global_metrics();
        assert!(std::ptr::eq(metrics, global_metrics()));
    }

    #[test]
    fn test_metrics_registration() {
        let metrics = GatewayMetrics::new().expect("Failed to create metrics");
        let registry = Registry::new();
        assert!(metrics.register(&registry).is_ok());
    }

    #[test]
    fn test_record_cache_hit() {
        let metrics = global_metrics();
        metrics.record_cache_hit(
            CacheTier::L0Moka,
            "v4-pro",
            Some("test_consumer"),
            Some("test-domain"),
        );
    }

    #[test]
    fn test_record_upstream_usage() {
        let metrics = global_metrics();
        metrics.record_upstream_usage(
            100,
            50,
            80,
            20,
            "v4-pro",
            Some("test_consumer"),
            Some("test-domain"),
        );
    }

    #[test]
    fn test_record_latency() {
        let metrics = global_metrics();
        metrics.record_latency(
            LatencyKind::Upstream,
            Duration::from_millis(100),
            "v4-pro",
            None,
        );
        metrics.record_latency(
            LatencyKind::CacheFetch,
            Duration::from_micros(500),
            "v4-pro",
            Some(CacheTier::L0Moka),
        );
    }
}
